### ISSUE TITLE
Parse config with library rather than manually

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-deploy#10]
Just came across this while setting up prettier: https://github.com/davidtheclark/cosmiconfig

> Find and load a configuration object from
> * a package.json property (anywhere up the directory tree)
> * a JSON or YAML "rc file" (anywhere up the directory tree)
> * a .config.js CommonJS module (anywhere up the directory tree)

That's what prettier uses to set their config, probably good for us to do the same thing rather than doing it manually like we are.

**Comment by SaFrMo** [comment]
Great catch! Added in 4dcd9aa.
