### ISSUE TITLE
Fail gracefully if .deploy.config.js is missing

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-deploy#3]
Currently it is easy to not have `.deploy.config.js` in the repo (if you clone an existing site from GitHub for example). I ran `npm run build` and got a lot of scary looking errors. It should give some instruction about the need to have a `.deploy.config.js` file and where to find the .example file.

**Comment by SaFrMo** [comment]
Fixed this in 1.1.0 - added an automatic config file generator when the file is missing.
