### ISSUE TITLE
Add ability to ignore files or directories if they already exist

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/fh-deploy#6]
For example, once I've uploaded the fonts to a site, I don't want to re-upload them - the files don't change and it takes forever. Maybe we can have a one-time list in .deployrc? Something like:

```js
queue: [

],
lazyQueue: [

]
```

where `lazyQueue` won't upload its matches if they already exist.

Not sure how to incorporate this into the `package.json` fallback, though, or even if we can.

**Comment by johndigital** [comment]
Maybe a cleaner way to do this would be reading the last modified time stamps? While the script is going through the files there could just be a check that if there is an existing file on the server with the same name, and the "last modified" timestamp of the local file is before or equal to the timestamp of the one on the server, skip it.

Would also be good to have control of that feature with a true/false property in the config file or something. What do you think?

**Comment by SaFrMo** [comment]
Yep, I like both of those thoughts a lot! The config prop could be something like `lazy` that's just a boolean. If true, only upload those files that have a last-modified timestamp later than the corresponding file on the server.

I'll dig into this and see if it's doable!

**Comment by SaFrMo** [comment]
Added in 779cb46!
